[object_store]
# Point to a GCS bucket. NOTE: we use HMAC auth interop
type = "s3"
access_key_id = "GOOG...changeme"
secret_access_key = "changeme"
endpoint = "https://storage.googleapis.com"
bucket = "seafowl-gcsfuse"

[catalog]
type = "sqlite"
dsn = "seafowl-data/seafowl.sqlite"

[frontend.http]
bind_host = "0.0.0.0"
write_access = "changeme" # see https://seafowl.io/docs/guides/querying-http#changing-the-password