[object_store]
# Point to a GCS bucket. NOTE: we use HMAC auth interop
type = "gcs"
bucket = "seafowl-gcsfuse"
google_application_credentials = "/app/seafowl-data/seafowl-gcsfuse.json"

[catalog]
type = "sqlite"
dsn = "seafowl-data/seafowl.sqlite"

[frontend.http]
bind_host = "0.0.0.0"
write_access = "changeme" # see https://seafowl.io/docs/guides/querying-http#changing-the-password